name: dbt_CI

on:
  pull_request:
    branches: [main]

jobs:
  ci_run:
    runs-on: ubuntu-latest
    env:
      # These variables allow the Action to auto-configure the "default" connection
      SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: "tasty_bytes_dbt_db"
      SNOWFLAKE_SCHEMA: "PUBLIC"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Execute Snowflake CLI command
        run: |
          snow --version
          snow connection test -x

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Install dbt Dependencies
        run: |
          cd tasty_bytes_dbt_demo
          dbt deps

      - name: Deploy Project
        run: |
          snow dbt deploy tasty_bytes \
            --source tasty_bytes_dbt_demo \
            --profiles-dir tasty_bytes_dbt_demo \
            --force

      - name: Execute Slim CI (Build Modified)
        # Note: If this fails with "State not found", change to --select path:models/
        run: |
          snow dbt execute tasty_bytes build --select state:modified+
