name: dbt_CI

on:
  pull_request:
    branches: [main]

jobs:
  ci_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Create Snowflake Config
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          authenticator = "SNOWFLAKE_JWT"
          private_key_raw = """${{ secrets.SNOWFLAKE_PRIVATE_KEY }}"""
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "tasty_bytes_dbt_db"
          schema = "PUBLIC"
          EOF
          chmod 0600 ~/.snowflake/config.toml

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Install dbt Dependencies
        run: |
          cd tasty_bytes_dbt_demo
          dbt deps

      - name: Deploy Project
        run: |
          snow dbt deploy tasty_bytes \
            --source tasty_bytes_dbt_demo \
            --profiles-dir tasty_bytes_dbt_demo \
            --force

      - name: Execute Slim CI (Build Modified)
        run: |
          snow dbt execute tasty_bytes build
