name: dbt_CI

on:
  pull_request:
    branches: [main]

jobs:
  ci_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python and Snowflake CLI
        run: |
          pip install snowflake-cli-labs dbt-snowflake

      - name: Run dbt CI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_DATABASE: tasty_bytes_dbt_db
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          snow dbt deploy tasty_bytes \
            --source tasty_bytes_dbt_demo \
            --profiles-dir tasty_bytes_dbt_demo \
            --default-target dev \
            --temporary-connection \
            --account "${{ secrets.SNOWFLAKE_ACCOUNT }}" \
            --user "${{ secrets.SNOWFLAKE_USER }}" \
            --private-key-file <(echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}") \
            --authenticator "SNOWFLAKE_JWT" \
            --role "${{ secrets.SNOWFLAKE_ROLE }}" \
            --warehouse "${{ secrets.SNOWFLAKE_WAREHOUSE }}" \
            --database "tasty_bytes_dbt_db" \
            --force
